
version: '2'

services:
  reactapp:
    image: reactapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2000:2000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 scripts/start.js