
version: '2'

services:
  app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 80:3000
      - 27018:27017
    volumes:
      - .:/usr/src/app